// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIhx9HbVQCHTDIAxRSBilxpQvAjNwKbCg',
    appId: '1:52614601603:web:2000fab1e056a96dadb4b6',
    messagingSenderId: '52614601603',
    projectId: 'akademik-3ceff',
    authDomain: 'akademik-3ceff.firebaseapp.com',
    storageBucket: 'akademik-3ceff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCngDIOJMN940ARQMEsX8EY36QUtEJzjOM',
    appId: '1:52614601603:android:0d8963de9faa2446adb4b6',
    messagingSenderId: '52614601603',
    projectId: 'akademik-3ceff',
    storageBucket: 'akademik-3ceff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA9yWZsBPSogIZwaUQOvsNYGLx-Znp6hU',
    appId: '1:52614601603:ios:b760ad7ef9f6a5f1adb4b6',
    messagingSenderId: '52614601603',
    projectId: 'akademik-3ceff',
    storageBucket: 'akademik-3ceff.firebasestorage.app',
    iosBundleId: 'com.example.akademik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA9yWZsBPSogIZwaUQOvsNYGLx-Znp6hU',
    appId: '1:52614601603:ios:b760ad7ef9f6a5f1adb4b6',
    messagingSenderId: '52614601603',
    projectId: 'akademik-3ceff',
    storageBucket: 'akademik-3ceff.firebasestorage.app',
    iosBundleId: 'com.example.akademik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIhx9HbVQCHTDIAxRSBilxpQvAjNwKbCg',
    appId: '1:52614601603:web:1e7daba6e079af4eadb4b6',
    messagingSenderId: '52614601603',
    projectId: 'akademik-3ceff',
    authDomain: 'akademik-3ceff.firebaseapp.com',
    storageBucket: 'akademik-3ceff.firebasestorage.app',
  );
}
